import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { pretendard } from "./font";
import Header from "@/components/layouts/Header";
import LayoutWrapper from "@/components/layouts/LayoutWrapper";

export const metadata: Metadata = {
  title: "같이달림",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} bg-gray-100 antialiased`}>
        <Providers>
          <Header />
          <LayoutWrapper>{children}</LayoutWrapper>
        </Providers>
      </body>
    </html>
  );
}
